DISABLE_LINTERS:
  - COPYPASTE
  - SPELL
  - REPOSITORY

MARKDOWN_MARKDOWNLINT_ARGUMENTS: "--disable MD033"

APPLY_FIXES: false
VALIDATE_ALL_CODEBASE: false
FLAVOR_SUGGESTIONS: false
GITHUB_ACTIONS_CHECKOV: false